### ISSUE TITLE
squash plugin removes required `docker_version` key

### ISSUE THREAD

**Issue by twaugh** [DBuildService/dock#124]
The dock-pulp plugin fails when the squash plugin is in use because the squash plugin removes the `docker_version` key from the metadata.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dock-1.3.0-py2.7.egg/dock/plugin.py", line 211, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/dock-1.3.0-py2.7.egg/dock/plugins/post_push_to_pulp.py", line 202, in run
    uploader.push_tarball_to_pulp(image_names)
  File "/usr/lib/python2.7/site-packages/dock-1.3.0-py2.7.egg/dock/plugins/post_push_to_pulp.py", line 82, in push_tarball_to_pulp
    self._check_file()
  File "/usr/lib/python2.7/site-packages/dock-1.3.0-py2.7.egg/dock/plugins/post_push_to_pulp.py", line 36, in _check_file
    vers = dockpulp.imgutils.get_versions(metadata)
  File "/usr/lib/python2.7/site-packages/dockpulp/imgutils.py", line 50, in get_versions
    vers[image_id] = data['docker_version']
KeyError: 'docker_version'
```

**Comment by twaugh** [comment]
Reported at https://github.com/goldmann/docker-scripts/issues/28.

**Comment by TomasTomecek** [comment]
Fixed upstream. We need to verify the fix.

**Comment by twaugh** [comment]
Think this has been verified now, closing.
