### ISSUE TITLE
APIError(HTTPError('409 Client Error: Conflict',),) in remove_built_image plugin

### ISSUE THREAD

**Issue by mmilata** [DBuildService/dock#125]
```
2015-05-29 09:27:38,239 - dock.plugin - DEBUG - running plugin 'remove_built_image'
2015-05-29 09:27:38,239 - dock.plugin - INFO - running plugin instance with args: '{}'
2015-05-29 09:27:38,239 - dock.core - INFO - remove image from filesystem
2015-05-29 09:27:38,239 - dock.core - DEBUG - image_id = 'c54f0273f53a617c3936e59ebe4816c4b667c261c1fc930e0e6ac7d15f43f653'
2015-05-29 09:27:38,324 - dock.core - INFO - remove image from filesystem
2015-05-29 09:27:38,324 - dock.core - DEBUG - image_id = 'brew/rhel7:latest'
2015-05-29 09:27:38,349 - dock.plugin - WARNING - Plugin 'remove_built_image' raised an exception: 'APIError(HTTPError('409 Client Error: Conflict',),)'
2015-05-29 09:27:38,381 - dock.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dock/plugin.py", line 211, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/dock/plugins/post_remove_built_image.py", line 43, in run
    self.tasker.remove_image(ImageName.parse(self.workflow.pulled_base_image))
  File "/usr/lib/python2.7/site-packages/dock/core.py", line 427, in remove_image
    self.d.remove_image(image_id, force=force, noprune=noprune)  # returns None
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 789, in remove_image
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 95, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 409 Client Error: Conflict ("Conflict, cannot delete 10acc31def5d because the running container 34ec1869229c is using it, stop it and use -f to force")

2015-05-29 09:27:38,382 - dock.plugin - INFO - Error is not fatal. Continuing...
```

I'm guessing that what happened here is the plugin tried to delete the base image but someone else was using it at the same time. We should probably wrap this in a try...catch block and ignore the error if that is the case.

**Comment by mmilata** [comment]
Now I can't reproduce it with master but stumbled into this one instead, with three concurrent builds:
```
2015-06-03 09:31:58,999 - dock.core - INFO - remove image from filesystem
2015-06-03 09:31:58,999 - dock.core - DEBUG - image_id = '9ad9260c5ec5f8521151184617b530bd58590d6b780b07b45b0baa927c8456c7'
2015-06-03 09:31:59,495 - dock.core - INFO - remove image from filesystem
2015-06-03 09:31:59,495 - dock.core - DEBUG - image_id = 'fedora:latest'
2015-06-03 09:31:59,501 - dock.plugin - WARNING - Plugin 'remove_built_image' raised an exception: 'APIError(HTT
2015-06-03 09:31:59,505 - dock.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/plugin.py", line 211, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/plugins/post_remove_built_image.py", line 43,
    self.tasker.remove_image(ImageName.parse(self.workflow.pulled_base_image))
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/core.py", line 454, in remove_image
    self.d.remove_image(image_id, force=force, noprune=noprune)  # returns None
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 826, in remove_image
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 119, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 404 Client Error: Not Found ("No such image: fedora:latest")

2015-06-03 09:31:59,505 - dock.plugin - INFO - Error is not fatal. Continuing...
```

**Comment by TomasTomecek** [comment]
Looks like we won't support concurrent builds :x

**Comment by mmilata** [comment]
We can support concurrent builds but each has to run on its own node:)

Anyway, if the first TB means that the image is used and will be deleted by the other build and the second TB that the image is already deleted (wtf?), then we can just ignore these errors. I'll poke this a bit more and then open PR to do this.

**Comment by TomasTomecek** [comment]
Looks like so.

I would definitely put info to logs that such errors happened.

**Comment by mmilata** [comment]
Ok, this is confusing ... I managed to reproduce this (it appears that you have to delete all tags of the base image prior to starting the builds). The confusing part is that the container that is using the base image is the build container itself:
```
# osc build-logs test-image1-20150603-150001
...
APIError: 409 Client Error: Conflict ("Conflict, cannot delete ded7cd95e059 because the running container 896d26987727 is using it, stop it and use -f to force")
...
# osc describe pod test-image1-20150603-150001
...
Events:
  FirstSeen                             LastSeen                        Count   From                    SubobjectPath                           Reason        Message
...
  Wed, 03 Jun 2015 09:00:02 -0400       Wed, 03 Jun 2015 09:00:02 -0400 1       {kubelet rhel71}        spec.containers{custom-build}           created       Created with docker id 896d269877278e987de585050cce61cf052edb8c754ec8e16e2139a7ee4ee10b
  Wed, 03 Jun 2015 09:00:02 -0400       Wed, 03 Jun 2015 09:00:02 -0400 1       {kubelet rhel71}        spec.containers{custom-build}           started       Started with docker id 896d269877278e987de585050cce61cf052edb8c754ec8e16e2139a7ee4ee10b
...
```
