### ISSUE TITLE
store_metadata_in_osv3 does not work without auth proxy

### ISSUE THREAD

**Issue by mmilata** [DBuildService/dock#134]
In current configuration the plugin tries to authenticate which fails:
```
2015-06-02 18:02:51,124 - dock.plugin - DEBUG - running plugin 'store_metadata_in_osv3'
2015-06-02 18:02:51,125 - dock.plugin - INFO - running plugin instance with args: '{u'url': u'https://rhel71:8443/osapi/v1beta1/', u'verify_ssl': False, u'use_auth': True}'
2015-06-02 18:02:51,125 - dock.plugins.store_metadata_in_osv3 - INFO - build id = test-image2-20150602-200232
2015-06-02 18:02:56,712 - osbs.core - ERROR - [401] 'Location' header is missing in response, cannot retrieve token
2015-06-02 18:02:56,712 - dock.plugin - WARNING - Plugin 'store_metadata_in_osv3' raised an exception: 'ValueError(u'Token was not retrieved successfully.',)'
2015-06-02 18:02:56,734 - dock.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/plugin.py", line 211, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/plugins/post_store_metadata_in_osv3.py", line 106, in run
    o.set_annotations_on_build(build_id, labels)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 312, in set_annotations_on_build
    build_json = self._get(url).json()
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 84, in _get
    headers, kwargs = self._request_args(with_auth, **kwargs)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 76, in _request_args
    raise ValueError("Token was not retrieved successfully.")
ValueError: Token was not retrieved successfully.

2015-06-02 18:02:56,735 - dock.plugin - INFO - Error is not fatal. Continuing...
```

If we pass `use_auth=false` to the plugin, it fails with:
```
2015-06-02 18:05:08,158 - dock.plugin - DEBUG - running plugin 'store_metadata_in_osv3'
2015-06-02 18:05:08,160 - dock.plugin - INFO - running plugin instance with args: '{u'url': u'https://rhel71:8443/osapi/v1beta1/', u'verify_ssl': False, u'use_auth': False}'
2015-06-02 18:05:08,160 - dock.plugins.store_metadata_in_osv3 - INFO - build id = test-image2-20150602-200448
2015-06-02 18:05:24,294 - osbs.core - ERROR - [400] {
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "Build in version v1beta1 cannot be handled as a Build: json: cannot unmarshal object into Go value of type string",
  "reason": "BadRequest",
  "code": 400
}
2015-06-02 18:05:24,294 - dock.plugin - WARNING - Plugin 'store_metadata_in_osv3' raised an exception: 'OsbsResponseException('{\n  "kind": "Status",\n  "creationTimestamp": null,\n  "apiVersion": "v1beta1",\n  "status": "Failure",\n  "message": "Build in version v1beta1 cannot be handled as a Build: json: cannot unmarshal object into Go value of type string",\n  "reason": "BadRequest",\n  "code": 400\n}',)'
2015-06-02 18:05:24,301 - dock.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/plugin.py", line 211, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/dock-1.3.2-py2.7.egg/dock/plugins/post_store_metadata_in_osv3.py", line 106, in run
    o.set_annotations_on_build(build_id, labels)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 316, in set_annotations_on_build
    check_response(response)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 35, in check_response
    raise OsbsResponseException(message=response.content, status_code=response.status_code)
OsbsResponseException: {
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta1",
  "status": "Failure",
  "message": "Build in version v1beta1 cannot be handled as a Build: json: cannot unmarshal object into Go value of type string",
  "reason": "BadRequest",
  "code": 400
}

2015-06-02 18:05:24,301 - dock.plugin - INFO - Error is not fatal. Continuing...
```

Perhaps porting osbs to v1beta3 api will solve this. And I guess we don't really support deployments without auth proxy anyway.

**Comment by TomasTomecek** [comment]
Ehm. This is new. Second thing should end with 401 and not with that weird trace. I'm actually using with_auth=false and it works fine for me.

**Comment by TomasTomecek** [comment]
Reproduced, this looks like a regression.

**Comment by mmilata** [comment]
This doesn't really solve the issue - perhaps you meant some other ticket number?

**Comment by TomasTomecek** [comment]
Hm, really? Could you please look into logs if there's some info what value openshift cannot unmarshal?
With the patch applied I no longer hit this.

**Comment by mmilata** [comment]
Damn, I thought it was supposed to fix the first stacktrace for some reason - haven't tried that one so the patch probably fixes it. I'll check.

Do you think we should patch osbs to set the `use_auth` plugin parameter depending on whether osbs itself was configured to use authentication?

**Comment by TomasTomecek** [comment]
I think it would make sense:

I've actually implemented for that purpose this config option: https://github.com/DBuildService/osbs/commit/b0a6d6a289d7a0e31c260a902d0287ba7f09e266

**Comment by mmilata** [comment]
Ok, tried with `use_auth=false` and it works. I totally missed the *metadata_plugin_use_auth* option. Nevertheless the *simple* build type does not use the option - see the referenced pull request.
