### ISSUE TITLE
Error when generating privileged-buildroot image: Exception caught: AttributeError("'generator' object has no attribute 'next'",)

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#25]
I followed git installation method, using 5b44df0cda8a66f0b5ef89ee1bbace846ad3b142.

When I try to create the `privileged-buildroot` image with the following command:

```
dock create-build-image --dock-local-path ~/git/dock/ ~/git/dock/images/privileged-builder privileged-buildroot
```

I get this:

```
running sdist
running egg_info
creating dock.egg-info
writing requirements to dock.egg-info/requires.txt
writing dock.egg-info/PKG-INFO
writing top-level names to dock.egg-info/top_level.txt
writing dependency_links to dock.egg-info/dependency_links.txt
writing entry points to dock.egg-info/entry_points.txt
writing manifest file 'dock.egg-info/SOURCES.txt'
reading manifest file 'dock.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dock.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating dock-1.0.0.a
creating dock-1.0.0.a/dock
creating dock-1.0.0.a/dock.egg-info
creating dock-1.0.0.a/dock/cli
creating dock-1.0.0.a/dock/plugins
creating dock-1.0.0.a/images
creating dock-1.0.0.a/images/dockerhost-builder
creating dock-1.0.0.a/images/privileged-builder
creating dock-1.0.0.a/tests
creating dock-1.0.0.a/tests/plugins
making hard links in dock-1.0.0.a...
hard linking LICENSE -> dock-1.0.0.a
hard linking MANIFEST.in -> dock-1.0.0.a
hard linking README.md -> dock-1.0.0.a
hard linking requirements.txt -> dock-1.0.0.a
hard linking setup.py -> dock-1.0.0.a
hard linking dock/__init__.py -> dock-1.0.0.a/dock
hard linking dock/api.py -> dock-1.0.0.a/dock
hard linking dock/build.py -> dock-1.0.0.a/dock
hard linking dock/buildimage.py -> dock-1.0.0.a/dock
hard linking dock/constants.py -> dock-1.0.0.a/dock
hard linking dock/core.py -> dock-1.0.0.a/dock
hard linking dock/inner.py -> dock-1.0.0.a/dock
hard linking dock/outer.py -> dock-1.0.0.a/dock
hard linking dock/plugin.py -> dock-1.0.0.a/dock
hard linking dock/util.py -> dock-1.0.0.a/dock
hard linking dock.egg-info/PKG-INFO -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/SOURCES.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/dependency_links.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/entry_points.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/requires.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/top_level.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock/cli/__init__.py -> dock-1.0.0.a/dock/cli
hard linking dock/cli/main.py -> dock-1.0.0.a/dock/cli
hard linking dock/plugins/__init__.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/input_env.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/input_osv3.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/input_path.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/plugin_rpmqa.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/post_store_logs_to_file.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_cp_dockerfile.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_inject_yum_repo.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_koji.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_pyrpkg_fetch_artefacts.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_return_dockerfile.py -> dock-1.0.0.a/dock/plugins
hard linking images/dockerhost-builder/Dockerfile -> dock-1.0.0.a/images/dockerhost-builder
hard linking images/privileged-builder/Dockerfile -> dock-1.0.0.a/images/privileged-builder
hard linking images/privileged-builder/docker.sh -> dock-1.0.0.a/images/privileged-builder
hard linking tests/plugins/__init__.py -> dock-1.0.0.a/tests/plugins
hard linking tests/plugins/test_yum_inject.py -> dock-1.0.0.a/tests/plugins
Writing dock-1.0.0.a/setup.cfg
Creating tar archive
removing 'dock-1.0.0.a' (and everything under it)
2015-01-22 19:40:50,927 - dock.core - INFO - build image from provided path
2015-01-22 19:40:50,951 - dock.core - INFO - build finished
2015-01-22 19:40:50,951 - dock - ERROR - Exception caught: AttributeError("'generator' object has no attribute 'next'",)
```

**Comment by TomasTomecek** [comment]
That's odd. Just tried it and it works for me.

It looks like an issue with docker-py. What versions of docker and docker-py you are using? If not latest, could you please update and try again?

If the issue persists, could you rerun it with option `-v`?

**Comment by goldmann** [comment]
Here is the list:

```
$ pip3 list
dock (1.0.0.a)
docker-py (0.7.1)
gitdb (0.6.4)
GitPython (0.3.6)
pip (1.5.6)
requests (2.4.3)
setuptools (2.0)
six (1.9.0)
smmap (0.9.0)
soco (0.7)
socos (0.1)
```

Please note that I didn't want to install it globally, so I was forced to [comment line 42](https://github.com/DBuildService/dock/blob/9966d14e238975b2c5956dbce8ac8d8b0243a39a/setup.py#L42). But that probably should be another bug report :)

When I try to run with `-v`, I get:

```
$ dock -v create-build-image --dock-local-path ~/git/dock/ ~/git/dock/images/privileged-builder privileged-buildroot
2015-01-28 15:58:39,063 - dock.buildimage - DEBUG - df_dir_path = '/home/goldmann/git/dock/images/privileged-builder', image = 'privileged-buildroot'
2015-01-28 15:58:39,064 - dock.buildimage - DEBUG - tmp dir with dockerfile '/tmp/tmph16e901r/df-6bcd56ee-d1c8-411b-9ff8-0bad876ed3e8' created
2015-01-28 15:58:39,065 - dock.buildimage - DEBUG - tmp dir with dock '/tmp/tmph16e901r/git-873f6d65-cb12-4a26-aae8-252c104ccf97' created
2015-01-28 15:58:39,065 - dock.buildimage - DEBUG - cp '/home/goldmann/git/dock/images/privileged-builder/Dockerfile' -> '/tmp/tmph16e901r/df-6bcd56ee-d1c8-411b-9ff8-0bad876ed3e8'
2015-01-28 15:58:39,065 - dock.buildimage - DEBUG - cp '/home/goldmann/git/dock/images/privileged-builder/docker.sh' -> '/tmp/tmph16e901r/df-6bcd56ee-d1c8-411b-9ff8-0bad876ed3e8'
2015-01-28 15:58:39,065 - dock.buildimage - DEBUG - df dir: ['docker.sh', 'Dockerfile']
2015-01-28 15:58:39,066 - dock.buildimage - DEBUG - executing sdist command in directory '/home/goldmann/git/dock'
running sdist
running egg_info
writing requirements to dock.egg-info/requires.txt
writing dock.egg-info/PKG-INFO
writing top-level names to dock.egg-info/top_level.txt
writing dependency_links to dock.egg-info/dependency_links.txt
writing entry points to dock.egg-info/entry_points.txt
reading manifest file 'dock.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dock.egg-info/SOURCES.txt'
warning: sdist: standard file not found: should have one of README, README.rst, README.txt

running check
creating dock-1.0.0.a
creating dock-1.0.0.a/dock
creating dock-1.0.0.a/dock.egg-info
creating dock-1.0.0.a/dock/cli
creating dock-1.0.0.a/dock/plugins
creating dock-1.0.0.a/images
creating dock-1.0.0.a/images/dockerhost-builder
creating dock-1.0.0.a/images/privileged-builder
creating dock-1.0.0.a/tests
creating dock-1.0.0.a/tests/plugins
making hard links in dock-1.0.0.a...
hard linking LICENSE -> dock-1.0.0.a
hard linking MANIFEST.in -> dock-1.0.0.a
hard linking README.md -> dock-1.0.0.a
hard linking requirements.txt -> dock-1.0.0.a
hard linking setup.cfg -> dock-1.0.0.a
hard linking setup.py -> dock-1.0.0.a
hard linking dock/__init__.py -> dock-1.0.0.a/dock
hard linking dock/api.py -> dock-1.0.0.a/dock
hard linking dock/build.py -> dock-1.0.0.a/dock
hard linking dock/buildimage.py -> dock-1.0.0.a/dock
hard linking dock/constants.py -> dock-1.0.0.a/dock
hard linking dock/core.py -> dock-1.0.0.a/dock
hard linking dock/inner.py -> dock-1.0.0.a/dock
hard linking dock/outer.py -> dock-1.0.0.a/dock
hard linking dock/plugin.py -> dock-1.0.0.a/dock
hard linking dock/util.py -> dock-1.0.0.a/dock
hard linking dock.egg-info/PKG-INFO -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/SOURCES.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/dependency_links.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/entry_points.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/requires.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock.egg-info/top_level.txt -> dock-1.0.0.a/dock.egg-info
hard linking dock/cli/__init__.py -> dock-1.0.0.a/dock/cli
hard linking dock/cli/main.py -> dock-1.0.0.a/dock/cli
hard linking dock/plugins/__init__.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/input_env.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/input_osv3.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/input_path.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/plugin_rpmqa.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/post_store_logs_to_file.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_change_from_in_df.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_cp_dockerfile.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_inject_yum_repo.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_koji.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_pyrpkg_fetch_artefacts.py -> dock-1.0.0.a/dock/plugins
hard linking dock/plugins/pre_return_dockerfile.py -> dock-1.0.0.a/dock/plugins
hard linking images/dockerhost-builder/Dockerfile -> dock-1.0.0.a/images/dockerhost-builder
hard linking images/privileged-builder/Dockerfile -> dock-1.0.0.a/images/privileged-builder
hard linking images/privileged-builder/docker.sh -> dock-1.0.0.a/images/privileged-builder
hard linking tests/plugins/__init__.py -> dock-1.0.0.a/tests/plugins
hard linking tests/plugins/test_yum_inject.py -> dock-1.0.0.a/tests/plugins
copying setup.cfg -> dock-1.0.0.a
Writing dock-1.0.0.a/setup.cfg
Creating tar archive
removing 'dock-1.0.0.a' (and everything under it)
2015-01-28 15:58:39,222 - dock.core - INFO - build image from provided path
2015-01-28 15:58:39,222 - dock.core - DEBUG - image = 'privileged-buildroot', path = '/tmp/tmph16e901r/df-6bcd56ee-d1c8-411b-9ff8-0bad876ed3e8'
2015-01-28 15:58:39,249 - dock.core - INFO - build finished
2015-01-28 15:58:39,250 - dock.core - DEBUG - build time = 0:00:00.027604
Traceback (most recent call last):
  File "/home/goldmann/.local/bin/dock", line 9, in <module>
    load_entry_point('dock==1.0.0.a', 'console_scripts', 'dock')()
  File "/home/goldmann/.local/lib/python3.4/site-packages/dock/cli/main.py", line 146, in run
    cli.run()
  File "/home/goldmann/.local/lib/python3.4/site-packages/dock/cli/main.py", line 134, in run
    args.func(args)
  File "/home/goldmann/.local/lib/python3.4/site-packages/dock/cli/main.py", line 19, in cli_create_build_image
    b.create_image(args.dockerfile_dir_path, args.image, use_cache=args.use_cache)
  File "/home/goldmann/.local/lib/python3.4/site-packages/dock/buildimage.py", line 75, in create_image
    log = logs_gen.next()
AttributeError: 'generator' object has no attribute 'next'
```

**Comment by TomasTomecek** [comment]
now I get it:
> python3.4

You're the first one who tried it with python 3. Okay, will rerun tests with py3 and fix it.

**Comment by TomasTomecek** [comment]
Okay, so it's not as easy as I thought originally. Will defer this.

In meanwhile, use python 2 please.

**Comment by TomasTomecek** [comment]
Finally figured out what's wrong. Will resolve this soon. Hopefully.
https://github.com/DBuildService/dock/commit/09050ed721c719f4e00996669db5348d48156478
