### ISSUE TITLE
Improve the first impression when running dock without arguments

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#27]
When I run `dock` without argument I see this:

```
$ dock
2015-01-28 16:11:51,982 - dock - ERROR - Exception caught: AttributeError("'Namespace' object has no attribute 'func'",)
```

Instead I would expect the `--help` output.

**Comment by goldmann** [comment]
And version with `-v`:

```
$ dock -v
Traceback (most recent call last):
  File "/home/goldmann/.local/bin/dock", line 9, in <module>
    load_entry_point('dock==1.0.0.a', 'console_scripts', 'dock')()
  File "/home/goldmann/.local/lib/python3.4/site-packages/dock/cli/main.py", line 146, in run
    cli.run()
  File "/home/goldmann/.local/lib/python3.4/site-packages/dock/cli/main.py", line 134, in run
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by TomasTomecek** [comment]
Yeah, I haven't really touched user experience, there are still some features missing.

Thanks for this bug report. Will fix.

**Comment by TomasTomecek** [comment]
Second look. Seems like another python 3 issue. This is what I get with 2.7:
```shell
$ dock
usage: main.py [-h] [-v | -q] {build,create-build-image,inside-build} ...
main.py: error: too few arguments
```
