### ISSUE TITLE
Cannot build image with hostdocker build method

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#29]
I created the build image like this:

```
$ dock -v create-build-image --dock-local-path ~/git/dock/ ~/git/dock/images/dockerhost-builder dockerhost-builder
```

Then I tried to build the proper image like this:

```
$ dock -v build --method hostdocker --build-image dockerhost-builder --image test-image --git-url "git@github.com:jboss-dockerfiles/base.git"
2015-01-29 14:09:47,036 - dock.outer - INFO - build image
2015-01-29 14:09:47,038 - dock.core - INFO - build image in container using docker from host
2015-01-29 14:09:47,038 - dock.core - DEBUG - build image = 'dockerhost-builder', args = '{"git_dockerfile_path": null, "git_commit": null, "image": "test-image", "git_url": "git@github.com:jboss-dockerfiles/base.git", "target_registries": null, "parent_registry": null}'
2015-01-29 14:09:47,038 - dock.core - INFO - does image exists?
2015-01-29 14:09:47,038 - dock.core - DEBUG - image_id = 'dockerhost-builder'
2015-01-29 14:09:47,047 - dock.core - DEBUG - image exists: True
2015-01-29 14:09:47,048 - dock.core - INFO - create container from image and run it
2015-01-29 14:09:47,048 - dock.core - DEBUG - image = 'dockerhost-builder', command = 'None', create_kwargs = '{'volumes': ['/var/run/docker.sock', '/tmp/tmpdYhn71']}', start_kwargs = '{'binds': {'/var/run/docker.sock': {'bind': '/var/run/docker.sock', 'ro': True}, '/tmp/tmpdYhn71': {'bind': '/run/share/', 'rw': True}}}'
2015-01-29 14:09:47,741 - dock.core - DEBUG - container_id = '99fbd58b58808e0c58fc13da4861663abecbac5260a3bc1933fb5e5393e19aaf'
2015-01-29 14:09:47,885 - dock.core - INFO - wait for container to finish
2015-01-29 14:09:47,885 - dock.core - DEBUG - container = '99fbd58b58808e0c58fc13da4861663abecbac5260a3bc1933fb5e5393e19aaf'
2015-01-29 14:09:48,375 - dock.core - DEBUG - container finished with exit code 1
2015-01-29 14:09:48,376 - dock.core - INFO - get stdout of container
2015-01-29 14:09:48,376 - dock.core - DEBUG - container_id = '99fbd58b58808e0c58fc13da4861663abecbac5260a3bc1933fb5e5393e19aaf', stream = 'False'
```

The logs in the container say:

```
$ docker logs 99fbd58b58808e0c58fc13da4861663abecbac5260a3bc1933fb5e5393e19aaf
2015-01-29 13:09:48,085 - dock.inner - DEBUG - getting build json from input path
2015-01-29 13:09:48,107 - dock.plugin - DEBUG - running plugin 'path' with args: '{}'
2015-01-29 13:09:48,107 - dock.plugins.path - ERROR - couldn't read json from file '/run/share/build.json'
Traceback (most recent call last):
  File "/usr/bin/dock", line 9, in <module>
    load_entry_point('dock==1.0.0.a', 'console_scripts', 'dock')()
  File "/usr/lib/python2.7/site-packages/dock-1.0.0.a-py2.7.egg/dock/cli/main.py", line 146, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/dock-1.0.0.a-py2.7.egg/dock/cli/main.py", line 134, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/dock-1.0.0.a-py2.7.egg/dock/cli/main.py", line 44, in cli_inside_build
    build_inside(input=args.input, input_args=args.input_arg)
  File "/usr/lib/python2.7/site-packages/dock-1.0.0.a-py2.7.egg/dock/inner.py", line 169, in build_inside
    raise RuntimeError("No valid build json!")
RuntimeError: No valid build json!
```

I tried also different versions of `--git-url`, but it didn't change anything.

Am I doing it wrong or is it a bug?

**Comment by TomasTomecek** [comment]
this is really weird, will investigate tomorrow (I've changed the way dock process input within build container: there may be a bug in it)

**Comment by goldmann** [comment]
When I try to run this again using revision 0e31518cc19d423d6a99bdb9374e404491c687d1 I get:

```
$ dock -v create-build-image --dock-local-path ~/git/dock/ ~/git/dock/images/dockerhost-builder dockerhost-builder
Traceback (most recent call last):
  File "/home/goldmann/git/dock/dock/cli/main.py", line 172, in <module>
    run()
  File "/home/goldmann/git/dock/dock/cli/main.py", line 168, in run
    cli.run()
  File "/home/goldmann/git/dock/dock/cli/main.py", line 145, in run
    set_logging(logging.DEBUG)
  File "/home/goldmann/git/dock/dock/__init__.py", line 12, in set_logging
    logger = logging.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1567, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1031, in getLogger
    raise TypeError('A logger name must be string or Unicode')
TypeError: A logger name must be string or Unicode
```

**Comment by goldmann** [comment]
Created a new issue: #32 to cover the issue in the last comment.

**Comment by TomasTomecek** [comment]
Tried this with latest dock and it's working. Reopen if this is still issue for you.

Tested on RHEL 7 with SELinux on.
