### ISSUE TITLE
TypeError: A logger name must be string or Unicode

### ISSUE THREAD

**Issue by goldmann** [DBuildService/dock#32]
When I try to use dock and execute `build` or `create-build-image` tasks, it fails with:

```
$ dock -v create-build-image --dock-local-path ~/git/dock/ ~/git/dock/images/dockerhost-builder dockerhost-builder
Traceback (most recent call last):
  File "/home/goldmann/git/dock/dock/cli/main.py", line 172, in <module>
    run()
  File "/home/goldmann/git/dock/dock/cli/main.py", line 168, in run
    cli.run()
  File "/home/goldmann/git/dock/dock/cli/main.py", line 145, in run
    set_logging(logging.DEBUG)
  File "/home/goldmann/git/dock/dock/__init__.py", line 12, in set_logging
    logger = logging.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1567, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1031, in getLogger
    raise TypeError('A logger name must be string or Unicode')
TypeError: A logger name must be string or Unicode
```

```
$ dock -v build --target-registries 172.17.0.27:5000 --method privileged --build-image privileged-buildroot --image test-image --git-url "https://github.com/TomasTomecek/docker-hello-world.git"
Traceback (most recent call last):
  File "/home/goldmann/git/dock/dock/cli/main.py", line 172, in <module>
    run()
  File "/home/goldmann/git/dock/dock/cli/main.py", line 168, in run
    cli.run()
  File "/home/goldmann/git/dock/dock/cli/main.py", line 145, in run
    set_logging(logging.DEBUG)
  File "/home/goldmann/git/dock/dock/__init__.py", line 12, in set_logging
    logger = logging.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1567, in getLogger
    return Logger.manager.getLogger(name)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1031, in getLogger
    raise TypeError('A logger name must be string or Unicode')
TypeError: A logger name must be string or Unicode
```

This is revision 0e31518cc19d423d6a99bdb9374e404491c687d1.

**Comment by TomasTomecek** [comment]
I feel super silly now. Refactored some code a bit and didn't change `set_logging` calls everywhere.

I'm planning to work on test-suite and dock's stability in upcoming weeks since I feel like it's almost feature complete.

**Comment by goldmann** [comment]
Yay, thanks for the fix! ;)
