### ISSUE TITLE
post_store_metadata_in_osv3 plugin uses E_OPERATION_TIMEDOUT which isn't available on RHEL 7

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/dock#95]
My registry isn't reachable. After successful build post_store_metadata_in_osv3 plugin is called but it fails with following traceback:
```
2015-05-13T08:49:30.519886958Z 2015-05-13 04:49:30,518 - dock.inner - DEBUG - getting build json from input osv3
2015-05-13T08:49:30.520007045Z 2015-05-13 04:49:30,518 - dock.plugin - DEBUG - loading plugins from dir '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins'
2015-05-13T08:49:30.520020500Z 2015-05-13 04:49:30,518 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/__init__.py'
2015-05-13T08:49:30.520029152Z 2015-05-13 04:49:30,519 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/input_env.py'
2015-05-13T08:49:30.522766275Z 2015-05-13 04:49:30,521 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/input_osv3.py'
2015-05-13T08:49:30.533172987Z 2015-05-13 04:49:30,530 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/input_path.py'
2015-05-13T08:49:30.535896912Z 2015-05-13 04:49:30,535 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/post_push_to_pulp.py'
2015-05-13T08:49:30.538376777Z 2015-05-13 04:49:30,537 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/post_remove_built_image.py'
2015-05-13T08:49:30.541379464Z 2015-05-13 04:49:30,538 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/post_rpmqa.py'
2015-05-13T08:49:30.541591206Z 2015-05-13 04:49:30,541 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/post_store_logs_to_file.py'
2015-05-13T08:49:30.542619931Z 2015-05-13 04:49:30,542 - dock.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/post_store_metadata_in_osv3.py'
2015-05-13T08:49:30.910610541Z Traceback (most recent call last):
2015-05-13T08:49:30.910663541Z   File "/usr/bin/dock", line 9, in <module>
2015-05-13T08:49:30.910676586Z     load_entry_point('dock==1.2.0', 'console_scripts', 'dock')()
2015-05-13T08:49:30.910684729Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/cli/main.py", line 200, in run
2015-05-13T08:49:30.910709648Z     cli.run()
2015-05-13T08:49:30.910722536Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/cli/main.py", line 183, in run
2015-05-13T08:49:30.910730818Z     args.func(args)
2015-05-13T08:49:30.910738167Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/cli/main.py", line 74, in cli_inside_build
2015-05-13T08:49:30.910745999Z     build_inside(input=args.input, input_args=args.input_arg, substitutions=args.substitute)
2015-05-13T08:49:30.910753519Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/inner.py", line 277, in build_inside
2015-05-13T08:49:30.910761077Z     input_runner = InputPluginsRunner([{'name': input, 'args': cleaned_input_args}])
2015-05-13T08:49:30.910768165Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugin.py", line 370, in __init__
2015-05-13T08:49:30.910776155Z     super(InputPluginsRunner, self).__init__('InputPlugin', plugins_conf, *args, **kwargs)
2015-05-13T08:49:30.910800890Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugin.py", line 130, in __init__
2015-05-13T08:49:30.910809541Z     self.plugin_classes = self.load_plugins(plugin_class_name)
2015-05-13T08:49:30.910821996Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugin.py", line 151, in load_plugins
2015-05-13T08:49:30.910829758Z     f_module = imp.load_source("dock.plugins.%s" % module_name, f)
2015-05-13T08:49:30.910836952Z   File "/usr/lib/python2.7/site-packages/dock-1.2.0-py2.7.egg/dock/plugins/post_store_metadata_in_osv3.py", line 11, in <module>
2015-05-13T08:49:30.910845094Z     from osbs.core import Openshift
2015-05-13T08:49:30.910852358Z   File "build/bdist.linux-x86_64/egg/osbs/core.py", line 24, in <module>
2015-05-13T08:49:30.910860021Z   File "build/bdist.linux-x86_64/egg/osbs/http.py", line 76, in <module>
2015-05-13T08:49:30.910868086Z AttributeError: 'module' object has no attribute 'E_OPERATION_TIMEDOUT'
```
osbs (builder) runs on RHEL 7.1.

Maybe it could be fixed similarly to DBuildService/osbs@dbcdb2281c1d7aa41c336b5f70d1f4cee81d07a3

**Comment by TomasTomecek** [comment]
https://github.com/DBuildService/osbs/commit/dbcdb2281c1d7aa41c336b5f70d1f4cee81d07a3
https://github.com/DBuildService/osbs/commit/4c16021fff38ee11838cb0769010a7ed4ebf3b91
these two should should fix this
